export const BreakBlockToolTag = 'BreakBlockTool'
export const PlaceBlockToolTag = 'PlaceBlockTool'
export const DoorTag = 'Door'
export const ShipTag = 'Ship'
export const ShooterTag = 'Shooter'
export const SpinTag = 'Spin'
