name: Release Beta

on:
  push:
    branches: [main]
    paths-ignore:
      - "README.md"

concurrency:
  group: beta_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.JS
        uses: bahmutov/npm-install@v1

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build project
        run: yarn build

      - name: Deploy Place to Roblox
        run: rbxcloud experience publish -f StationA33.rbxl -p 129543241385348 -u 7305222931 -t published -a ${{ secrets.ROBLOX_API_KEY }}
